buildDocker:
  allow_failure: false
  stage: build
  image: docker:19.03.8
  when: always
  tags:
    - docker
    - leviathan
  script:
    - rm src/composer.lock
    - ash ci/pipelines/build/docker/build.sh
