version: '3'

services:
  webserver:
    networks:
      - directusapi_default
    environment:
      - LETSENCRYPT_EMAIL=testbestellung@etribes.de
      - LETSENCRYPT_HOST=skillz.etribes.de
      - VIRTUAL_HOST=skillz.etribes.de
      - VIRTUAL_PORT=8080